version: "3.8"

services:
  # 1. MariaDB
  mariadb:
    image: masjeong/mariadb:1.0    # 직접 빌드한 이미지 사용
    container_name: mariadb
    restart: always
    ports:
      - "3307:3306" # 외부 3307 → maria 컨테이너 3306 노출
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      TZ: Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - ecommerce-network

  # 2. Config Service
  config-service:
    image: config-service:latest
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GIT_SSH_KEY_PATH=/root/.ssh/github_rsa # Git SSH 키 경로
    volumes:
      - ./keystore/github_key/rsa_github_key:/root/.ssh/github_rsa:ro # 호스트 SSH 키를 컨테이너에 읽기전용으로 마운트
      - ./keystore/github_key/known_hosts:/root/.ssh/known_hosts:ro  # known_hosts 마운트
      - ./keystore/apiEncryptionKey.jks:/app/keystore/apiEncryptionKey.jks:ro
      - ./keystore/publicKey.jks:/app/keystore/publicKey.jks:ro
      - ./keystore/trustServer.cer:/app/keystore/trustServer.cer:ro
    depends_on:
      - mariadb
    networks:
      - ecommerce-network

  # 3. Eureka Discovery
  discoveryservice:
    image: discoveryservice:latest
    container_name: discoveryservice
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_URI=http://config-service:8888
    depends_on:
      - config-service
    networks:
      - ecommerce-network

  # 4. API Gateway (Eureka, Config 이후)
  apigateway-service:
    image: apigateway-service:latest
    container_name: apigateway-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_URI=http://config-service:8888
      - EUREKA_URI=http://discoveryservice:8761/eureka
    depends_on:
      - config-service
      - discoveryservice
    networks:
      - ecommerce-network

  catalog-service:
    image: catalog-service:latest
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_URI=http://config-service:8888
      - EUREKA_URI=http://discoveryservice:8761/eureka
      - DB_HOST=mariadb
    depends_on:
      - mariadb
      - config-service
      - discoveryservice
    networks:
      - ecommerce-network

  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_URI=http://config-service:8888
      - EUREKA_URI=http://discoveryservice:8761/eureka
      - DB_HOST=mariadb
    depends_on:
      - mariadb
      - config-service
      - discoveryservice
    networks:
      - ecommerce-network

  order-service:
    image: order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_URI=http://config-service:8888
      - EUREKA_URI=http://discoveryservice:8761/eureka
      - DB_HOST=mariadb
    depends_on:
      - mariadb
      - config-service
      - discoveryservice
    networks:
      - ecommerce-network

volumes:
  mariadb_data:

networks:
  ecommerce-network:
    driver: bridge