server:
  port: ${SERVER_PORT:8085}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%thread] [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  level:
    com.example.userservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework: INFO
    root: INFO
    org.hibernate.SQL: DEBUG
    # springboot 3.x hibernate 6버전 이상 바인딩된 파라미터 로그 설정
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  application:
    name: file-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # SQL 쿼리에 주석 추가
        highlight_sql: true
  # RabbitMQ 설정 정보
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://${DB_HOST}:3306/user_db
#    username: root
#    password: root
  h2:
    console:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

  # 0번포트(랜덤포트)를 사용하게되면 애플리케이션을 여러개 실행했어도 Eureka서버에 1개만 실행되는 것처럼 보인다.
  # 이를 방지하기 위해 사용하는 옵션(instance-id)
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Eureka Server로 heartbeat 전송하는 시간 (디폴트 30초)
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

webdav:
  username: "jihun"
  password: "40102987"
  base-url: "http://192.168.35.100/webdav"