server:
  port: 0 # 8081

spring:
  application:
    name: my-first-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # discoveryservice
  instance:
#    prefer-ip-address: true # 기본 로컬 호스트 대신 호스트의 IP를 설정하는 구성
#    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}