server:
  port: ${SERVER_PORT:8084}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%thread] [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  level:
    com.example.cartservice: INFO
    org.springframework: INFO
    root: INFO

spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus