services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper # zookeeper가 먼저 실행되어야 하므로 의존성 설정
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes  # PLAINTEXT 프로토콜 허용
      - KAFKA_ENABLE_KRAFT=no # KRAFT 모드 비활성화
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true  # 자동으로 토픽 생성할 수 있도록 설정
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181  # zookeeper 연결 정보
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094 # kafka가 수신할 리스너
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094 # kafka 클라이언트가 사용할 리스너 주소
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT  # 각 리스너에 보안 프로토콜 설정

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - 9091:8080
    restart: always
    environment:
      - DYNAMIC_CONFIG_ENABLED=true # 동적 구성 허용
      - KAFKA_CLUSTERS_0_NAME=masjeong_kafka  # kafka 클러스터 이름 설정
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092  # kafka 클러스터에 연결할 부트스트랩 서버 설정